# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#publishing-using-gradle

name: Gradle Publish

on:
  release:
    types: [created]

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 13
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
    - name: Build with Gradle
      run: gradle build
    - name: Publish to Sonatype
      run: gradle publish
      # yoh nico, it's you from the past
      # you saved this private and password somewhere, just try to remember it
      env:
        MVN_PGP_PRIVATE_KEY: ${{ secrets.MVN_PGP_PRIVATE_KEY }}
        MVN_PGP_PRIVATE_KEY_PASSWORD: ${{ secrets.MVN_PGP_PRIVATE_KEY_PASSWORD }}
        SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
        SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
    - name: Release to central
      run: gradle closeAndReleaseRepository
      env:
        SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
        SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
